#!/usr/bin/env bash
# Write the Homebrew formula (CLI) and cask (app) for a release into
# packaging/homebrew/, from the release's assets on GitHub (draft or
# published), and push them to the tap daniel-farina/homebrew-godterm.
#
#   scripts/release/homebrew.sh v0.2.0          write and push
#   NO_PUSH=1 scripts/release/homebrew.sh v0.2.0  write only
#
# The URLs are the release's public download links (no token needed).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPO="${REPO:-daniel-farina/godterm}"
TAP="${TAP:-daniel-farina/homebrew-godterm}"
tag="${1:?usage: homebrew.sh <tag>}"
v="${tag#v}"
fv="${v%%-*}" # artifact names carry the Cargo version (0.2.0 for v0.2.0-rc2)
OUT="$ROOT/packaging/homebrew"
mkdir -p "$OUT/Formula" "$OUT/Casks"

rel="$(gh api "repos/$REPO/releases?per_page=50" --jq ".[] | select(.tag_name == \"$tag\")")"
[[ -n "$rel" ]] || { echo "no release $tag on $REPO" >&2; exit 1; }
sums="$(mktemp)"
sums_id="$(jq -r '.assets[] | select(.name == "SHA256SUMS") | .id' <<< "$rel")"
gh api -H "Accept: application/octet-stream" "repos/$REPO/releases/assets/$sums_id" > "$sums"

asset() { # asset <name> -> "<api url> <sha256>"
  local id sha
  id="$(jq -r --arg n "$1" '.assets[] | select(.name == $n) | .id' <<< "$rel")"
  [[ -n "$id" ]] || { echo "release $tag has no $1" >&2; exit 1; }
  sha="$(awk -v n="$1" '$2 == n || $2 == "*" n {print $1}' "$sums")"
  [[ -n "$sha" ]] || { echo "SHA256SUMS has no $1" >&2; exit 1; }
  echo "$(jq -r --arg n "$1" '.assets[] | select(.name == $n) | .browser_download_url' <<< "$rel") $sha"
}
read -r mac_url mac_sha <<< "$(asset "godterm-$fv-macos-universal.zip")"
read -r dmg_url dmg_sha <<< "$(asset "GodTerm-$fv-macos-universal.dmg")"
read -r lx_url lx_sha <<< "$(asset "godterm-$fv-x86_64-unknown-linux-gnu.tar.gz")"
read -r la_url la_sha <<< "$(asset "godterm-$fv-aarch64-unknown-linux-gnu.tar.gz")"
rm -f "$sums"
for x in "$mac_url" "$mac_sha" "$dmg_url" "$dmg_sha" "$lx_url" "$lx_sha" "$la_url" "$la_sha"; do
  [[ -n "$x" ]] || { echo "missing an asset url or checksum; nothing written" >&2; exit 1; }
done

cat > "$OUT/Formula/godterm.rb" <<EOF
# Generated by scripts/release/homebrew.sh for $tag. Do not edit by hand.
class Godterm < Formula
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/$REPO"
  version "$v"
  license "MIT"

  on_macos do
    url "$mac_url"
    sha256 "$mac_sha"
  end

  on_linux do
    on_intel do
      url "$lx_url"
      sha256 "$lx_sha"
    end
    on_arm do
      url "$la_url"
      sha256 "$la_sha"
    end
    depends_on "alsa-lib"
  end

  def install
    # godterm finds godterm-speech next to its real path, so both live in
    # libexec and bin gets a link.
    libexec.install "godterm"
    libexec.install "godterm-speech" if File.exist?("godterm-speech")
    bin.install_symlink libexec/"godterm"
  end

  def caveats
    <<~TEXT
      GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
      Voice is optional: brew install ffmpeg whisper-cpp, then run godterm doctor.
    TEXT
  end

  test do
    assert_match version.to_s.split("-").first, shell_output("#{bin}/godterm --version")
  end
end
EOF

cat > "$OUT/Casks/godterm.rb" <<EOF
# Generated by scripts/release/homebrew.sh for $tag. Do not edit by hand.
cask "godterm" do
  version "$v"
  sha256 "$dmg_sha"

  url "$dmg_url"
  name "GodTerm"
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/$REPO"

  container type: :dmg
  depends_on macos: ">= :monterey"
  conflicts_with formula: "godterm"

  app "GodTerm.app"
  binary "#{appdir}/GodTerm.app/Contents/MacOS/godterm"

  zap trash: [
    "~/.godterm",
  ]

  caveats <<~TEXT
    GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
  TEXT
end
EOF
echo "wrote $OUT/Formula/godterm.rb and $OUT/Casks/godterm.rb for $tag"

[[ -n "${NO_PUSH:-}" ]] && exit 0
work="${CARGO_TARGET_DIR:-$ROOT/target-release-eng}/homebrew-tap"
rm -rf "$work"
gh repo clone "$TAP" "$work" -- -q
mkdir -p "$work/Formula" "$work/Casks"
cp "$OUT/Formula/godterm.rb" "$work/Formula/"
cp "$OUT/Casks/godterm.rb" "$work/Casks/"
cp "$OUT/TAP_README.md" "$work/README.md"
git -C "$work" add Formula/godterm.rb Casks/godterm.rb README.md
if git -C "$work" diff --cached --quiet; then echo "tap already up to date"; exit 0; fi
git -C "$work" commit -q -m "godterm $v"
git -C "$work" push -q origin HEAD
echo "pushed godterm $v to $TAP"
