# Generated by scripts/release/homebrew.sh for v0.2.0-rc4. Do not edit by hand.
# Private release assets: export HOMEBREW_GITHUB_API_TOKEN (repo scope).
cask "godterm" do
  version "0.2.0-rc4"
  sha256 "25b494e3d4806178dfc4c7337d2b204eeb49a6c5379042b8232ed9f6b651e99e"

  url "https://api.github.com/repos/daniel-farina/godterm/releases/assets/617644545",
      header: ["Accept: application/octet-stream", "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}"]
  name "GodTerm"
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"

  container type: :dmg
  depends_on macos: ">= :monterey"
  conflicts_with formula: "godterm"

  app "GodTerm.app"
  binary "#{appdir}/GodTerm.app/Contents/MacOS/godterm"

  zap trash: [
    "~/.godterm",
  ]

  caveats <<~TEXT
    GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
  TEXT
end
