# Generated by scripts/release/homebrew.sh for v0.2.0-rc4. Do not edit by hand.
# Private release assets: export HOMEBREW_GITHUB_API_TOKEN (repo scope).
class Godterm < Formula
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"
  version "0.2.0-rc4"
  license :cannot_represent

  on_macos do
    url "https://api.github.com/repos/daniel-farina/godterm/releases/assets/617644912",
        headers: ["Accept: application/octet-stream", "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}"]
    sha256 "ab13588f8c57a42cd6aaaf649013a5e665b30197acc589410c7c84d0253ce60a"
  end

  on_linux do
    on_intel do
      url "https://api.github.com/repos/daniel-farina/godterm/releases/assets/617645369",
          headers: ["Accept: application/octet-stream", "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}"]
      sha256 "8fd2ffd7df6243057c425cafc817cb479311a95a98e7f4baf5c3a28ded71d27e"
    end
    on_arm do
      url "https://api.github.com/repos/daniel-farina/godterm/releases/assets/617645272",
          headers: ["Accept: application/octet-stream", "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}"]
      sha256 "41c470419350121a6a8813053124bb522f72ba15991b1a08a5bbbf2f40ec7017"
    end
    depends_on "alsa-lib"
  end

  def install
    # godterm finds godterm-speech next to its real path, so both live in
    # libexec and bin gets a link.
    libexec.install "godterm"
    libexec.install "godterm-speech" if File.exist?("godterm-speech")
    bin.install_symlink libexec/"godterm"
  end

  def caveats
    <<~TEXT
      GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
      Voice is optional: brew install ffmpeg whisper-cpp, then run godterm doctor.
    TEXT
  end

  test do
    assert_match version.to_s.split("-").first, shell_output("#{bin}/godterm --version")
  end
end
